apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: 'mysecretpassword'
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false