{
 "title": "Test Automation Health",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "project", "query": "select project from launch" },
   {
    "name": "launch_name",
    "label": "launch",
    "query": "select launch_name from launch where project='$project'"
   },
   {
    "name": "platform",
    "label": "platform",
    "query": "select platform from launch where launch_name='$launch_name'"
   }
  ]
 },
 "panels": [
  {
   "title": "Launch Health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  health\nFROM launch\nWHERE\n  $__timeFilter(created_at) AND\n  project = '$project' AND\n  launch_name = '$launch_name' AND\n  platform = '$platform'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Launch Health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  health\nFROM launch\nWHERE\n  $__timeFilter(created_at) AND\n  project = '$project' AND\n  launch_name = '$launch_name' AND\n  platform = '$platform'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "timeseries",
   "description": "Avg % of passed + failed due to product bug results.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  reliability\nFROM launch\nWHERE\n  $__timeFilter(created_at) AND\n  project = '$project' AND\n  launch_name = '$launch_name' AND\n  platform = '$platform'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "description": "Avg launch frequency, launch per X hours",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  launch_frequency\nFROM launch\nWHERE\n  $__timeFilter(created_at) AND\n  project = '$project' AND\n  launch_name = '$launch_name' AND\n  platform = '$platform'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "Avg launch duration, minutes",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  duration_minutes\nFROM launch\nWHERE\n  $__timeFilter(created_at) AND\n  project = '$project' AND\n  launch_name = '$launch_name' AND\n  platform = '$platform'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Tests Count",
   "type": "timeseries",
   "description": "Latest launch in query tests count",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  tests_count\nFROM launch\nWHERE\n  $__timeFilter(created_at) AND\n  project = '$project' AND\n  launch_name = '$launch_name' AND\n  platform = '$platform'\nORDER BY 1"
    }
   ]
  }
 ]
}